version: '0.1'

services:
    python-jupyter:
        image: fastai-docker
        volumes:
            - fastai-docker:/data
        ports: 
            - "8888:8888"
        command: jupyter notebook --ip 0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password=''

volumes:
    fastai-volume:
