version: '3.3'

services:
    python-jupyter:
        build: .
        volumes:
            - notebook-volume:/data
        ports: 
            - "8888:8888"
        command: jupyter notebook --ip 0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password=''

volumes:
    notebook-volume:
